spring.application.name=my-pad
server.port=5172

spring.datasource.url=jdbc:sqlite:./data/dontpad.db
spring.datasource.driver-class-name=org.sqlite.JDBC
spring.datasource.hikari.maximum-pool-size=10

spring.sql.init.mode=always
spring.jpa.database-platform=org.hibernate.dialect.SQLiteDialect
spring.mvc.pathmatch.matching-strategy=ant_path_matcher
